### ISSUE TITLE
File Page and upload files not working

### ISSUE THREAD

**Issue by hadi060** [codelyfe/WP-FILEBASE-PRO-RESTORED#1]
Hello,
Thank you very much for your work to get back this great plugin to life, but after testing it in a localhost website, I noticed two big issues:
1. File page feature is not working,
2. When I tried to upload a new file, it keeps spinning without uploading it.
Can you check it again, please? As the official copy has issues in my live websites, so I'm looking for an updated version that can work on latest PHP versions.
Thank you.

**Comment by codelyfe** [comment]
Thank you for reaching out. Sorry it took so long to reply but I will look into those issues.

**Comment by codelyfe** [comment]
Issue should be resolved. Let me know if there are any other errors.

**Comment by hadi060** [comment]
Thank you very much, but the file page issue is still there, I mean when enabling the "File Pages" option to make downloading begin after some seconds, that feature is not working.
Thank you in advance for checking it.

**Comment by codelyfe** [comment]
I see what you mean. Ill take a look at it today for sure.

**Comment by hadi060** [comment]
> I see what you mean. Ill take a look at it today for sure.

Thank you very much. Waiting for your updates.

**Comment by hadi060** [comment]
Hello,
Sorry for the inconvenience, but I would like to know if there is anything new regarding this issue.
Thank you.

**Comment by codelyfe** [comment]
Not yet. Keep running into issues... It might be to far outdated to bring back to life...

**Comment by sandporg** [comment]
@hadi060 Hi, I'm working on a lite replacement for WP-Filebase Pro. It's lacking a lot of the features but it does offer easy migration and handling of files [https://github.com/rsandb/file-version-manager](https://github.com/rsandb/file-version-manager)

It's still being developed so there are some things that aren't quite working but you can track the progress at that github repo. Also feel free to point out any bugs or feature requests!
